<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/Cholesky_decomp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cholesky Decomposition

In [ ]:
import numpy as np
from numpy.linalg import cholesky

A = np.array([[1, 2, -1], [2, 6, 0], [-1, 0, 9]])

print(A)

L = cholesky(A)

print(L)

print(np.dot(L, L.T))

[[ 1  2 -1]
 [ 2  6  0]
 [-1  0  9]]
[[ 1.          0.          0.        ]
 [ 2.          1.41421356  0.        ]
 [-1.          1.41421356  2.44948974]]
[[ 1.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [ 2.00000000e+00  6.00000000e+00 -4.05861454e-17]
 [-1.00000000e+00 -4.05861454e-17  9.00000000e+00]]
