<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/cofactor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 余因子または小行列式を求める関数
def cofactor(a, i, j, minor=False):
    x = np.delete(a, i, axis=0) # i行目を削除
    x = np.delete(x, j, axis=1) # j列目を削除
    if minor == False: # 余因子の場合
        a_ij = (-1)**(i+j) * np.linalg.det(x) # 小行列式に符号をかける
    else: # 小行列式の場合
        a_ij = np.linalg.det(x)
    return a_ij

# n次正方行列Aの余因子行列を求める関数
def cofactor_matrix(a):
    n = len(a) # 行列のサイズ
    c = np.zeros((n,n)) # すべての成分が0のn×n行列を生成
    for i in range(n):
        for j in range(n):
            c[j,i] = cofactor(a, i, j) # (j,i)成分に余因子を代入
    return c


In [12]:

# 行列Aを定義（例として3×3行列）
a = np.array([[2, 7, 3],
              [5, 0, 9],
              [3, 1, 4]])

# 行列Aの余因子行列を求める
c = cofactor_matrix(a)

# 結果を表示
print("A:")
print(a)
print("C:")
print(c)

det = np.linalg.det(a)
print('det=', det)

AC = np.dot(a, c)/det
print('A*C/det')
print(AC)

Ainv = det*np.linalg.inv(a)
print('det*Ainv')
print(Ainv)



A:
[[2 7 3]
 [5 0 9]
 [3 1 4]]
C:
[[ -9. -25.  63.]
 [  7.  -1.  -3.]
 [  5.  19. -35.]]
det= 46.00000000000002
A*C/det
[[ 1.00000000e+00 -5.40630342e-16  1.54465812e-16]
 [-3.28239851e-16  1.00000000e+00  1.54465812e-16]
 [-2.31698718e-16 -9.26794873e-16  1.00000000e+00]]
det*Ainv
[[ -9. -25.  63.]
 [  7.  -1.  -3.]
 [  5.  19. -35.]]
