<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pythonを用いた線形代数


広島大学大学院先進理工系科学研究科 
教授 栗田多喜夫


## numpyによる線形代数


    numpy を利用するためにパッケージをimportします．

In [1]:
import numpy as np
print(np.__version__)

1.19.2


## ベクトルと行列の定義

### ベクトル

In [2]:
x = np.array([1,2,3])
print('x\n', x)


x
 [1 2 3]


### 行列

In [3]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


### 転置

In [4]:
AT = np.transpose(A)
print(AT)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
# 省略表記
AT = A.T
print(AT)

[[1 4]
 [2 5]
 [3 6]]


### 回転行列

\begin{align*}
R(\theta) = \begin{bmatrix} \cos \theta & - \sin \theta \\ \sin \theta & \cos \theta \end{bmatrix}
\end{align*}

In [6]:
def R(th):
    R = np.array([[np.cos(th), -np.sin(th)],
                  [np.sin(th),  np.cos(th)]])
    return R

print(R(np.pi/4))

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


### 単位行列

\begin{align*}
I =
 \begin{bmatrix}
 1 & 0   & \cdots & 0 \\
 0   & 1 & \cdots & 0 \\
 \vdots & \vdots & \ddots & \vdots \\
 0   & 0   & \cdots & 1
 \end{bmatrix}
 = \mbox{diag}(1,1,\ldots,1) = [\delta_{ij}]
\end{align*}

In [7]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### ベクトルの内積

\begin{align*}
 {\bf{x}}^T {\bf{y}} = \begin{bmatrix} x_1 & x_2 & \cdots & x_m \end{bmatrix} \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_m \end{bmatrix} 
 = \sum_{i=1}^m x_i y_i = {\bf{y}}^T {\bf{x}}
\end{align*}


In [8]:
x = np.array([1,2,3])
y = np.array([4,-5,6])
print(np.dot(x,y))
# 省略表記
print(x.dot(y))

12
12


### ベクトルのノルム（長さ）

$$
||{\bf{x}}|| = \sqrt{{\bf{x}}^T{\bf{x}}} = \sqrt{ x_1^2+x_2^2 + \cdots + x_m^2}
  = \sqrt{\sum_{i=1}^m x_i^2}
$$


In [9]:
print(x)
print(1**2+2++2+3**2)
xnorm = np.linalg.norm(x)
print(xnorm**2)

[1 2 3]
14
14.0


### 行列とベクトルの積

$$
 {\bf{y}} = A {\bf{x}}
 =
 \begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1n} \\
 a_{21} & a_{22} & \cdots & a_{2n} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mn}
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
 \begin{bmatrix}
 \sum_{j=1} a_{1j} x_j \\
 \sum_{j=1} a_{2j} x_j \\
 \vdots \\
 \sum_{j=1} a_{mj} x_j
 \end{bmatrix}
$$

In [10]:
A = np.array([[1,2,3],[1,2,-1]])
print('A\n', A)
x = np.array([4, -5, 6])
print('x\n',x)
Ax = np.dot(A,x)
print('A x\n', Ax)

# 省略表現
Ax = A.dot(x)
print('A x\n', Ax)

# 簡単表現
Ax = A @ x
print('A x\n', Ax)


A
 [[ 1  2  3]
 [ 1  2 -1]]
x
 [ 4 -5  6]
A x
 [ 12 -12]
A x
 [ 12 -12]
A x
 [ 12 -12]


### 行列の積

In [11]:
A = np.array([[1,2,3],[1,2,-1]])
print('A\n', A)
B = np.array([[4, 1], [-5, 1], [6, 1]])
print('B\n',B)
AB = np.dot(A,B)
print('A B\n', AB)

# 省略表現
AB = A.dot(B)
print('A B\n', AB)

# 簡単表現
AB = A @ B
print('A B\n', AB)


A
 [[ 1  2  3]
 [ 1  2 -1]]
B
 [[ 4  1]
 [-5  1]
 [ 6  1]]
A B
 [[ 12   6]
 [-12   2]]
A B
 [[ 12   6]
 [-12   2]]
A B
 [[ 12   6]
 [-12   2]]


### 正方行列のトレース

$$
 tr(A) =
 \begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mm}
 \end{bmatrix} = a_{11} + a_{22} + \cdots + a_{mm}
$$

In [12]:
A=np.array([[1,2,3], [2,2,2], [-4, -3, -2]])
print('A\n', A)
print('trace of A = ', np.trace(A))

A
 [[ 1  2  3]
 [ 2  2  2]
 [-4 -3 -2]]
trace of A =  1


### トレースの性質

$$
    tr(A+B) = tr(A) + tr(B)
$$
    あるいは，
$$
    tr(AB) = tr(BA)
$$


In [13]:
A=np.array([[1,2,3], [2,2,2], [-4, -3, -2]])
print('A\n', A)
print('trace of A = ', np.trace(A))
B=np.array([[1,1,1], [2,2,2], [3,3,3]])
print('B\n', B)
print('trace of B = ', np.trace(B))

# tr(A+B)
print('\n=== tr(A+B) = tr(A) + tr(B) ===')
print('trace of A + B = ', np.trace(A+B))
print('tr(A) + tr(B) = ', np.trace(A) + np.trace(B))

# trac(AB)
print('\n=== tr(AB) = tr(BA) ===')
print('tr(AB) = ', np.trace(A.dot(B)))
print('tr(BA) = ', np.trace(B.dot(A)))

A
 [[ 1  2  3]
 [ 2  2  2]
 [-4 -3 -2]]
trace of A =  1
B
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
trace of B =  6

=== tr(A+B) = tr(A) + tr(B) ===
trace of A + B =  7
tr(A) + tr(B) =  7

=== tr(AB) = tr(BA) ===
tr(AB) =  10
tr(BA) =  10


### 2次形式

$$
      {\bf{x}}^T A {\bf{x}} = \begin{bmatrix} x_1 &  x_2 & \cdots & x_m \end{bmatrix}
      \begin{bmatrix}
        a_{11} & a_{12} & \cdots & a_{1m} \\
        a_{21} & a_{22} & \cdots & a_{2m} \\
        \vdots & \vdots & \ddots & \vdots \\
        a_{m1} & a_{m2} & \cdots & a_{mm}
      \end{bmatrix}
      \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_m \end{bmatrix}
      = \sum_{i=1}^m \sum_{j=1}^m a_{ij} x_i x_j
$$

In [14]:
A=np.array([[1,2,3], [2,2,2], [3, 2, 3]])
print('A\n', A)
b = np.array([1,-2,1])
print('b\n', b)
qf = np.dot(b.T, A.dot(b))
print('b^TAb = ', qf)


A
 [[1 2 3]
 [2 2 2]
 [3 2 3]]
b
 [ 1 -2  1]
b^TAb =  2


### フロベニウスノルム

\begin{align*}
  ||A|| = \sqrt{\sum_{i=1}^m \sum_{j=1}^n a_{ij}^2}
\end{align*}


In [15]:
A=np.array([[1,2,3], [4,5,6]])
print('A\n', A)
print('Frobenius norm = ', np.linalg.norm(A))

# tr(A A^T)
print('\n=== tr(A A^T) ===')
AAT = A.dot(A.T)
print('A A^T\n', AAT)
trAAT = np.trace(AAT)
print('tr(A A^T) = ', trAAT)
print('sqrt(tr(A A^T)) = ', np.sqrt(trAAT))

# tr(A^T A)
print('\n=== tr(A^T A) ===')
ATA = np.dot(A.T, A)
print('A^T A\n', ATA)
trATA = np.trace(ATA)
print('tr(A^T A) = ', trATA)
print('sqrt(tr(A^T A)) = ', np.sqrt(trATA))


A
 [[1 2 3]
 [4 5 6]]
Frobenius norm =  9.539392014169456

=== tr(A A^T) ===
A A^T
 [[14 32]
 [32 77]]
tr(A A^T) =  91
sqrt(tr(A A^T)) =  9.539392014169456

=== tr(A^T A) ===
A^T A
 [[17 22 27]
 [22 29 36]
 [27 36 45]]
tr(A^T A) =  91
sqrt(tr(A^T A)) =  9.539392014169456


### 行列の簡約化（Raw Echelon Form)

sympy を用いて，行列
$$
\begin{bmatrix}
2 & 3 & 6 \\
4 & 5 & 7
\end{bmatrix}
$$
の簡約化をしてみる．

In [16]:
import sympy as sym

In [17]:
A = sym.Matrix([[2,3,6],[4,5,7]])
print('A\n', A)
(B, Pv) = A.rref()
print(B)
B

A
 Matrix([[2, 3, 6], [4, 5, 7]])
Matrix([[1, 0, -9/2], [0, 1, 5]])


Matrix([
[1, 0, -9/2],
[0, 1,    5]])

### ランク

行列
$$
\begin{bmatrix}
1 & 0 & 2 & 1 \\
2 & 1 & 1 & 0 \\
0 & 1 & 1 & 0
\end{bmatrix}
$$
のランクを求めるために，この行列を簡約化してみる．

In [18]:
A=sym.Matrix([[1,0,2,1], [2,1,1,0], [0,1,1,0]])
print('A\n', A)
(B, Pv) = A.rref()
B

A
 Matrix([[1, 0, 2, 1], [2, 1, 1, 0], [0, 1, 1, 0]])


Matrix([
[1, 0, 0,    0],
[0, 1, 0, -1/2],
[0, 0, 1,  1/2]])

これから，この行列のランクは，３であるとわかる．

### numpy でのランクの計算

次に，numpyで同じ行列のランクを計算してみる．

In [19]:
A=np.array([[1,0,2,1], [2,1,1,0], [0,1,1,0]])
print('A\n', A)
print('rank(A)=', np.linalg.matrix_rank(A))

A
 [[1 0 2 1]
 [2 1 1 0]
 [0 1 1 0]]
rank(A)= 3


### LU分解

\begin{align*}
    A = P L U
\end{align*}

In [20]:
import numpy as np
from scipy.linalg import lu

# pylint: disable=invalid-name

A = np.array([[1, 2, 2],
              [2, 5, 6],
              [3, 8, 12]])

print("LU decomposition (A = PLU): ")
print("A:\n", A)
P, L, U = lu(A)
print("P: \n", P)
print("L: \n", L)
print("U: \n", U)
print("PLU: \n", P @ L @ U)

LU decomposition (A = PLU): 
A:
 [[ 1  2  2]
 [ 2  5  6]
 [ 3  8 12]]
P: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L: 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]]
U: 
 [[ 3.          8.         12.        ]
 [ 0.         -0.66666667 -2.        ]
 [ 0.          0.         -1.        ]]
PLU: 
 [[ 1.  2.  2.]
 [ 2.  5.  6.]
 [ 3.  8. 12.]]


### 連立方程式の解 

scipyを利用

\begin{align*}
    \begin{bmatrix} 3 & 2 & 0 \\ 1 & -1 & 0 \\ 0 & 5 & 1 \end{bmatrix} 
    \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = 
    \begin{bmatrix} 2 \\ 4 \\ -1 \end{bmatrix}
\end{align*}

In [21]:
#importing the scipy and numpy packages
from scipy import linalg
import numpy as np

#Declaring the numpy arrays
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

m, n = A.shape

print('m=', m, 'n=', n)

# Augmented matrx [A b]
Ab = np.column_stack((A, b))
print("[A b]\n", Ab)

rankA = np.linalg.matrix_rank(A)
rankAb = np.linalg.matrix_rank(Ab)

print("Rank A=", rankA, "Rank [A b]=", rankAb)

if (rankA != rankAb):
    print("There is no solution!!!")
elif (n != rankA):
    print("There is no uniqe solution\n")
else:
    
    # Determinant of A
    detA = linalg.det(A)
    print("Determinant is", detA)

    #Passing the values to the solve function
    x = linalg.solve(A, b)

    #printing the result array
    print("The solurion is ", x)

    # A x
    print("A x =", A.dot(x))


m= 3 n= 3
[A b]
 [[ 3  2  0  2]
 [ 1 -1  0  4]
 [ 0  5  1 -1]]
Rank A= 3 Rank [A b]= 3
Determinant is -5.0
The solurion is  [ 2. -2.  9.]
A x = [ 2.  4. -1.]


### 逆行列

行列
$$
A=\begin{bmatrix}
2 & 1 & 1 \\
1 & 2 & 1 \\
1 & 1 & 2
\end{bmatrix}
$$
の逆行列を求める


In [22]:
A=np.array([[2,1,1],[1,2,1],[1,1,2]])
print('A\n', A)
Ainv = np.linalg.inv(A)
print('Inverse of A\n', Ainv)

# Check for A A^{-1}=I
print('A A^{-1}\n', A.dot(Ainv))

A
 [[2 1 1]
 [1 2 1]
 [1 1 2]]
Inverse of A
 [[ 0.75 -0.25 -0.25]
 [-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]]
A A^{-1}
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00]]


### 行列式

行列式の計算

In [23]:
A=np.array([[1,-1,2],[2,1,1],[-1,-1,1]])
print('A\n', A)
B=np.array([[1,3,-1], [-1,1,-1], [1,1,-3]])
print('B\n', B)

# det(A)
detA = np.linalg.det(A)
print("det(A) = ", detA)

# det(A^T)
detAT = np.linalg.det(A.T)
print("det(A^T) = ", detAT)

# det(A^{-1})
detAinv = np.linalg.det(np.linalg.inv(A))
print("det(A^{-1}) = ", detAinv)

# det(B)
detB = np.linalg.det(B)
print("det(B) = ", detB)

# det(B^T)
detBT = np.linalg.det(B.T)
print("det(B^T) = ", detBT)

# det(B^{-1})
detBinv = np.linalg.det(np.linalg.inv(B))
print("det(B^{-1}) = ", detBinv)

# det(AB)
detAB = np.linalg.det(A.dot(B))
print("det(AB)=", detAB)

A
 [[ 1 -1  2]
 [ 2  1  1]
 [-1 -1  1]]
B
 [[ 1  3 -1]
 [-1  1 -1]
 [ 1  1 -3]]
det(A) =  2.9999999999999996
det(A^T) =  2.9999999999999996
det(A^{-1}) =  0.3333333333333333
det(B) =  -12.0
det(B^T) =  -12.0
det(B^{-1}) =  -0.08333333333333333
det(AB)= -36.0


### 固有値と固有ベクトル


In [24]:
A=np.array([[0,-1],[1,0]])
print('A\n', A)

[E, V] = np.linalg.eig(A)
print('Eigen Values\n', E)
print('Eiven Vectors\n', V)

A
 [[ 0 -1]
 [ 1  0]]
Eigen Values
 [0.+1.j 0.-1.j]
Eiven Vectors
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


これ例から，行列$A$が実行列での固有値や固有ベクトルは複素数になることがわかる

### 固有値と固有ベクトル

3次実対称行列の場合

In [25]:
A=np.array([[1,2,3], [2,2,1],[3,1,3]])
print('A\n', A)

[L, U] = np.linalg.eig(A)
print('Eigen Values\n', L)
print('Eiven Vectors\n', U)

A
 [[1 2 3]
 [2 2 1]
 [3 1 3]]
Eigen Values
 [ 6.14389545 -1.52834667  1.38445123]
Eiven Vectors
 [[ 0.57392741  0.81866166 -0.02001012]
 [ 0.4431767  -0.33105373 -0.83306533]
 [ 0.68862307 -0.46925101  0.55281258]]


実対象行列の固有値，固有ベクトルは実数となることがわかる．


この行列の対角化

In [26]:
print("Eigen Values\n", np.diag(L))
print("U^T A U\n", np.dot(U.T, np.dot(A, U)))

Eigen Values
 [[ 6.14389545  0.          0.        ]
 [ 0.         -1.52834667  0.        ]
 [ 0.          0.          1.38445123]]
U^T A U
 [[ 6.14389545e+00 -2.77555756e-16 -6.66133815e-16]
 [-8.88178420e-16 -1.52834667e+00  3.33066907e-16]
 [ 0.00000000e+00  3.33066907e-16  1.38445123e+00]]


### スペクトル分解

In [45]:
print("A\n", A)
print("U L U^{T}\n", np.dot(U, np.dot(np.diag(L), U.T)))

A
 Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
U L U^{T}
 [[1. 2. 3.]
 [2. 2. 1.]
 [3. 1. 3.]]


### 特異値分解


In [28]:
B=np.array([[1,2,3], [2,2,2]])
print('B\n', B)

[S, D, V] = np.linalg.svd(B, full_matrices=True)

print('S\n', S)
print('D\n', D)
print('V^T\n', V)

print('S D V^T\n', np.dot(S * D, V[:2,:]))


B
 [[1 2 3]
 [2 2 2]]
S
 [[ 0.73588229 -0.67710949]
 [ 0.67710949  0.73588229]]
D
 [5.00415773 0.97898183]
V^T
 [[ 0.41767294  0.56472711  0.71178129]
 [ 0.81171587  0.12006923 -0.57157741]
 [ 0.40824829 -0.81649658  0.40824829]]
S D V^T
 [[1. 2. 3.]
 [2. 2. 2.]]


### 一般化逆行列（Moore–Penrose inverse）

[特異値分解との関係]

$A$の特異値分解が，
$$
A = U D V^T
$$
で与えられる時，一般化逆行列$A^{+}$は，
$$
A^{+} = V D^{+} U^{T}
$$
で与えられる．ここで，$D^{+}$は，０以外の対角要素はその逆数をとり，0はそのままにした対角行列

これから，
$$
 A A^{+} = U D V^{T} V D^{+} U^{T} = U D D^{+} U^{T} = U U^{T} = I
$$
となることが確かめられる．


In [49]:
from numpy.linalg import pinv

A = np.array([[1,2,3], [2,2,2]])
print('A\n', A)

PinvA = pinv(A)

print('Moore-Penrose pseudo-invers\n', PinvA)

print('A PinvA\n', np.dot(A, PinvA))

A
 [[1 2 3]
 [2 2 2]]
Moore-Penrose pseudo-invers
 [[-5.00000000e-01  6.66666667e-01]
 [-6.93889390e-17  1.66666667e-01]
 [ 5.00000000e-01 -3.33333333e-01]]
A PinvA
 [[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]


## sympy を用いた線形代数

行列の宣言

In [30]:
A = sym.Matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


   ”ｓｙｍｐｙ．Matrix” をnumpy.arrayに変換

In [31]:
A_n = sym.matrix2numpy(A)
print(A_n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


零行列

In [32]:
Zero = sym.Matrix.zeros(2, 3)
print(Zero)

Matrix([[0, 0, 0], [0, 0, 0]])


単位行列

In [33]:
I = sym.Matrix.eye(3,3)
print(I)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


対角行列

In [34]:
D = sym.Matrix.diag(1,2,3)
print(D)

Matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])


In [35]:
print(A)
print(A[1,2])
print(A[0,0])
print(A[5])

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
6
1
6


In [36]:
B=sym.Matrix([[7,8,9],[4,5,6],[1,2,3]])
print(A)
print(B)
print(A * B)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Matrix([[7, 8, 9], [4, 5, 6], [1, 2, 3]])
Matrix([[18, 24, 30], [54, 69, 84], [90, 114, 138]])


行列の簡約化（Raw Echelon Form)

In [37]:
print("A={}".format(A))
(G, Pv) = A.rref()
print("G={}".format(G))

A=Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
G=Matrix([[1, 0, -1], [0, 1, 2], [0, 0, 0]])


行列のランク

In [38]:
print(A.rank())
print(B.rank())
print((A * B - I).rank())

2
2
3


行列の逆行列

In [39]:
C=A * B - I
Cinv = C.inv()
print(Cinv)
print(C * Cinv)

Matrix([[-65/137, 33/137, -6/137], [81/274, -371/548, 48/137], [9/137, 111/274, -35/137]])
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
