## sympy を用いた線形代数

In [ ]:
import sympy as sym

行列の宣言

In [7]:
A = sym.Matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


   ”ｓｙｍｐｙ．Matrix” をnumpy.arrayに変換

In [8]:
A_n = sym.matrix2numpy(A)
print(A_n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


零行列

In [9]:
Zero = sym.Matrix.zeros(2, 3)
print(Zero)

Matrix([[0, 0, 0], [0, 0, 0]])


単位行列

In [12]:
I = sym.Matrix.eye(3,3)
print(I)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


対角行列

In [14]:
D = sym.Matrix.diag(1,2,3)
print(D)

Matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])


In [19]:
print(A)
print(A[1,2])
print(A[0,0])
print(A[5])

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
6
1
6


In [20]:
B=sym.Matrix([[7,8,9],[4,5,6],[1,2,3]])
print(A)
print(B)
print(A * B)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Matrix([[7, 8, 9], [4, 5, 6], [1, 2, 3]])
Matrix([[18, 24, 30], [54, 69, 84], [90, 114, 138]])


行列の簡約化（Raw Echelon Form)

In [23]:
print("A={}".format(A))
(G, Pv) = A.rref()
print("G={}".format(G))

A=Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
G=Matrix([[1, 0, -1], [0, 1, 2], [0, 0, 0]])


In [ ]:
行列のランク

In [29]:
print(A.rank())
print(B.rank())
print((A * B - I).rank())

2
2
3


行列の逆行列

In [31]:
C=A * B - I
Cinv = C.inv()
print(Cinv)
print(C * Cinv)

Matrix([[-65/137, 33/137, -6/137], [81/274, -371/548, 48/137], [9/137, 111/274, -35/137]])
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


### numpy, scipyを用いて線形代数

LU分解
\begin{align*}
    A = P L U
\end{align*}

In [2]:
import numpy as np
from scipy.linalg import lu

# pylint: disable=invalid-name

A = np.array([[1, 2, 2],
              [2, 5, 6],
              [3, 8, 12]])

print("LU decomposition (A = PLU): ")
print("A:\n", A)
P, L, U = lu(A)
print("P: \n", P)
print("L: \n", L)
print("U: \n", U)
print("PLU: \n", P @ L @ U)

LU decomposition (A = PLU): 
A:
 [[ 1  2  2]
 [ 2  5  6]
 [ 3  8 12]]
P: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L: 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]]
U: 
 [[ 3.          8.         12.        ]
 [ 0.         -0.66666667 -2.        ]
 [ 0.          0.         -1.        ]]
PLU: 
 [[ 1.  2.  2.]
 [ 2.  5.  6.]
 [ 3.  8. 12.]]


連立方程式の解 by using scipy
\begin{align*}
    \begin{bmatrix} 3 & 2 & 0 \\ 1 & -1 & 0 \\ 0 & 5 & 1 \end{bmatrix} 
    \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = 
    \begin{bmatrix} 2 \\ 4 \\ -1 \end{bmatrix}
\end{align*}

In [5]:
#importing the scipy and numpy packages
from scipy import linalg
import numpy as np

#Declaring the numpy arrays
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

m, n = A.shape

print('m=', m, 'n=', n)

# Augmented matrx [A b]
Ab = np.column_stack((A, b))
print("[A b]\n", Ab)

rankA = np.linalg.matrix_rank(A)
rankAb = np.linalg.matrix_rank(Ab)

print("Rank A=", rankA, "Rank [A b]=", rankAb)

if (rankA != rankAb):
    print("There is no solution!!!")
elif (n != rankA):
    print("There is no uniqe solution\n")
else:
    
    # Determinant of A
    detA = linalg.det(A)
    print("Determinant is", detA)

    #Passing the values to the solve function
    x = linalg.solve(A, b)

    #printing the result array
    print("The solurion is ", x)

    # A x
    print("A x =", A.dot(x))


m= 3 n= 3
[A b]
 [[ 3  2  0  2]
 [ 1 -1  0  4]
 [ 0  5  1 -1]]
Rank A= 3 Rank [A b]= 3
Determinant is -5.0
The solurion is  [ 2. -2.  9.]
A x = [ 2.  4. -1.]
