----
title: "Titre"
date: Fecha
output:
    pdf_document:
        includes:
            in_header: mystyles.sty
----

## Pythonを用いた線形代数

### numpyによる線形代数

In [1]:
import numpy as np


ベクトル

In [4]:
x = np.array([1,2,3])
print('x\n', x)


x
 [1 2 3]


行列

In [5]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


転置

In [8]:
AT = np.transpose(A)
print(AT)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
# 省略表記
AT = A.T
print(AT)

[[1 4]
 [2 5]
 [3 6]]


回転行列
\begin{align*}
R(\theta) = \begin{bmatrix} \cos \theta & - \sin \theta \\ \sin \theta & \cos \theta \end{bmatrix}
\end{align*}

In [14]:
def R(th):
    R = np.array([[np.cos(th), -np.sin(th)],
                  [np.sin(th),  np.cos(th)]])
    return R

print(R(np.pi/4))

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


単位行列

\begin{align*}
I =
 \begin{bmatrix}
 1 & 0   & \cdots & 0 \\
 0   & 1 & \cdots & 0 \\
 \vdots & \vdots & \ddots & \vdots \\
 0   & 0   & \cdots & 1
 \end{bmatrix}
 = \mbox{diag}(1,1,\ldots,1) = [\delta_{ij}]
\end{align*}

In [20]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


内積
\begin{align*}
 {\bf{x}}^T {\bf{y}} = \begin{bmatrix} x_1 & x_2 & \cdots & x_m \end{bmatrix} \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_m \end{bmatrix} 
 = \sum_{i=1}^m x_i y_i = {\bf{y}}^T {\bf{x}}
\end{align*}


In [24]:
x = np.array([1,2,3])
y = np.array([4,-5,6])
print(np.dot(x,y))
# 省略表記
print(x.dot(y))

12
12


ベクトルのノルム（長さ）
$$
||{\bf{x}}|| = \sqrt{{\bf{x}}^T{\bf{x}}} = \sqrt{ x_1^2+x_2^2 + \cdots + x_m^2}
  = \sqrt{\sum_{i=1}^m x_i^2}
$$


In [34]:
print(x)
print(1**2+2++2+3**2)
xnorm = np.linalg.norm(x)
print(xnorm**2)

[1 2 3]
14
14.0


行列とベクトルの積
$$
 {\bf{y}} = A {\bf{x}}
 =
 \begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1n} \\
 a_{21} & a_{22} & \cdots & a_{2n} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mn}
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
 \begin{bmatrix}
 \sum_{j=1} a_{1j} x_j \\
 \sum_{j=1} a_{2j} x_j \\
 \vdots \\
 \sum_{j=1} a_{mj} x_j
 \end{bmatrix}
$$

In [41]:
A = np.array([[1,2,3],[1,2,-1]])
print('A\n', A)
x = np.array([4, -5, 6])
print('x\n',x)
Ax = np.dot(A,x)
print('A x\n', Ax)

# 省略表現
Ax = A.dot(x)
print('A x\n', Ax)

# 簡単表現
Ax = A @ x
print('A x\n', Ax)


A
 [[ 1  2  3]
 [ 1  2 -1]]
x
 [ 4 -5  6]
A x
 [ 12 -12]
A x
 [ 12 -12]
A x
 [ 12 -12]


行列の積

In [44]:
A = np.array([[1,2,3],[1,2,-1]])
print('A\n', A)
B = np.array([[4, 1], [-5, 1], [6, 1]])
print('B\n',B)
AB = np.dot(A,B)
print('A B\n', AB)

# 省略表現
AB = A.dot(B)
print('A B\n', AB)

# 簡単表現
AB = A @ B
print('A B\n', AB)


A
 [[ 1  2  3]
 [ 1  2 -1]]
B
 [[ 4  1]
 [-5  1]
 [ 6  1]]
A B
 [[ 12   6]
 [-12   2]]
A B
 [[ 12   6]
 [-12   2]]
A B
 [[ 12   6]
 [-12   2]]


正方行列のトレース
$$
 tr(A) =
 \begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mm}
 \end{bmatrix} = a_{11} + a_{22} + \cdots + a_{mm}
$$

In [45]:
A=np.array([[1,2,3], [2,2,2], [-4, -3, -2]])
print('A\n', A)
print('trace of A = ', np.trace(A))

A
 [[ 1  2  3]
 [ 2  2  2]
 [-4 -3 -2]]
trace of A =  1


トレースの性質
$$
    tr(A+B) = tr(A) + tr(B)
$$
    あるいは，
$$
    tr(AB) = tr(BA)
$$


In [54]:
A=np.array([[1,2,3], [2,2,2], [-4, -3, -2]])
print('A\n', A)
print('trace of A = ', np.trace(A))
B=np.array([[1,1,1], [2,2,2], [3,3,3]])
print('B\n', B)
print('trace of B = ', np.trace(B))

# tr(A+B)
print('\n=== tr(A+B) = tr(A) + tr(B) ===')
print('trace of A + B = ', np.trace(A+B))
print('tr(A) + tr(B) = ', np.trace(A) + np.trace(B))

# trac(AB)
print('\n=== tr(AB) = tr(BA) ===')
print('tr(AB) = ', np.trace(A.dot(B)))
print('tr(BA) = ', np.trace(B.dot(A)))

A
 [[ 1  2  3]
 [ 2  2  2]
 [-4 -3 -2]]
trace of A =  1
B
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
trace of B =  6

=== tr(A+B) = tr(A) + tr(B) ===
trace of A + B =  7
tr(A) + tr(B) =  7

=== tr(AB) = tr(BA) ===
tr(AB) =  10
tr(BA) =  10


## sympy を用いた線形代数

In [ ]:
import sympy as sym

行列の宣言

In [7]:
A = sym.Matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


   ”ｓｙｍｐｙ．Matrix” をnumpy.arrayに変換

In [8]:
A_n = sym.matrix2numpy(A)
print(A_n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


零行列

In [9]:
Zero = sym.Matrix.zeros(2, 3)
print(Zero)

Matrix([[0, 0, 0], [0, 0, 0]])


単位行列

In [12]:
I = sym.Matrix.eye(3,3)
print(I)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


対角行列

In [14]:
D = sym.Matrix.diag(1,2,3)
print(D)

Matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])


In [19]:
print(A)
print(A[1,2])
print(A[0,0])
print(A[5])

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
6
1
6


In [20]:
B=sym.Matrix([[7,8,9],[4,5,6],[1,2,3]])
print(A)
print(B)
print(A * B)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Matrix([[7, 8, 9], [4, 5, 6], [1, 2, 3]])
Matrix([[18, 24, 30], [54, 69, 84], [90, 114, 138]])


行列の簡約化（Raw Echelon Form)

In [23]:
print("A={}".format(A))
(G, Pv) = A.rref()
print("G={}".format(G))

A=Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
G=Matrix([[1, 0, -1], [0, 1, 2], [0, 0, 0]])


In [ ]:
行列のランク

In [29]:
print(A.rank())
print(B.rank())
print((A * B - I).rank())

2
2
3


行列の逆行列

In [31]:
C=A * B - I
Cinv = C.inv()
print(Cinv)
print(C * Cinv)

Matrix([[-65/137, 33/137, -6/137], [81/274, -371/548, 48/137], [9/137, 111/274, -35/137]])
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


### numpy, scipyを用いて線形代数

LU分解
\begin{align*}
    A = P L U
\end{align*}

In [2]:
import numpy as np
from scipy.linalg import lu

# pylint: disable=invalid-name

A = np.array([[1, 2, 2],
              [2, 5, 6],
              [3, 8, 12]])

print("LU decomposition (A = PLU): ")
print("A:\n", A)
P, L, U = lu(A)
print("P: \n", P)
print("L: \n", L)
print("U: \n", U)
print("PLU: \n", P @ L @ U)

LU decomposition (A = PLU): 
A:
 [[ 1  2  2]
 [ 2  5  6]
 [ 3  8 12]]
P: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L: 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]]
U: 
 [[ 3.          8.         12.        ]
 [ 0.         -0.66666667 -2.        ]
 [ 0.          0.         -1.        ]]
PLU: 
 [[ 1.  2.  2.]
 [ 2.  5.  6.]
 [ 3.  8. 12.]]


連立方程式の解 by using scipy
\begin{align*}
    \begin{bmatrix} 3 & 2 & 0 \\ 1 & -1 & 0 \\ 0 & 5 & 1 \end{bmatrix} 
    \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = 
    \begin{bmatrix} 2 \\ 4 \\ -1 \end{bmatrix}
\end{align*}

In [5]:
#importing the scipy and numpy packages
from scipy import linalg
import numpy as np

#Declaring the numpy arrays
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

m, n = A.shape

print('m=', m, 'n=', n)

# Augmented matrx [A b]
Ab = np.column_stack((A, b))
print("[A b]\n", Ab)

rankA = np.linalg.matrix_rank(A)
rankAb = np.linalg.matrix_rank(Ab)

print("Rank A=", rankA, "Rank [A b]=", rankAb)

if (rankA != rankAb):
    print("There is no solution!!!")
elif (n != rankA):
    print("There is no uniqe solution\n")
else:
    
    # Determinant of A
    detA = linalg.det(A)
    print("Determinant is", detA)

    #Passing the values to the solve function
    x = linalg.solve(A, b)

    #printing the result array
    print("The solurion is ", x)

    # A x
    print("A x =", A.dot(x))


m= 3 n= 3
[A b]
 [[ 3  2  0  2]
 [ 1 -1  0  4]
 [ 0  5  1 -1]]
Rank A= 3 Rank [A b]= 3
Determinant is -5.0
The solurion is  [ 2. -2.  9.]
A x = [ 2.  4. -1.]
