<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pythonを用いた線形代数


広島大学
名誉教授 栗田多喜夫


## numpyによる線形代数


numpy を利用するためにパッケージをimportします．

In [ ]:
import numpy as np
print(np.__version__)

## ベクトルと行列の定義

### ベクトル

numpyで1次元のベクトル（配列）を作って，それを変数$x$に代入してみます．

\begin{align*}
 x = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}
\end{align*}

In [ ]:
x = np.array([1,2,3])
print('x\n', x)


### 行列

同様に，$2 \times 3$の行列（２次元の配列）を作って，変数$A$に代入してみます．

\begin{align*}
 A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
\end{align*}

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

### 転置

 行列$A$の行と列を入れ替えた行列(転置)$A^T$を計算するには，transposeを使います．

In [ ]:
AT = np.transpose(A)
print(AT)

これは，省略形を用いて，次のように書くこともできます．

In [ ]:
# 省略表記
AT = A.T
print(AT)

### 回転行列

２次元の回転行列$R(\theta)$

\begin{align*}
R(\theta) = \begin{bmatrix} \cos \theta & - \sin \theta \\ \sin \theta & \cos \theta \end{bmatrix}
\end{align*}

を定義してみましょう．
この関数を使うと，任意の$\theta$に対して，回転行列＄R(\theta)$を計算することができます．
以下の例では，$R(\pi/4)$と$R(\pi/2)$を計算しています．


In [ ]:
def R(th):
    R = np.array([[np.cos(th), -np.sin(th)],
                  [np.sin(th),  np.cos(th)]])
    return R

print(R(np.pi/4))

print(R(np.pi/2))

### 単位行列

単位行列

\begin{align*}
I = \begin{bmatrix} 1 & 0   & \cdots & 0 \\ 0   & 1 & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0   & 0   & \cdots & 1 \end{bmatrix} = diag(1,1,\ldots,1) = [\delta_{ij}]
\end{align*}

は，numpy.eye関数を使うと生成することができます．ここで，引数は行列のサイズです．

以下のコードは，$3 \times 3$の単位行列を変数$I$に代入しています．


In [ ]:
I = np.eye(3)
print(I)

### ベクトルの内積

ベクトルの内積

\begin{align*}
 {\bf{x}}^T {\bf{y}} = \begin{bmatrix} x_1 & x_2 & \cdots & x_m \end{bmatrix} \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_m \end{bmatrix}
 = \sum_{i=1}^m x_i y_i = {\bf{y}}^T {\bf{x}}
\end{align*}

は，numpy.dot関数を用いて計算することができます．

省略形として，変数xの後にdot(y)をつけて，x.dot(y)のように書くこともできます．

In [ ]:
x = np.array([1,2,3])
y = np.array([4,-5,6])
print(np.dot(x,y))
# 省略表記
print(x.dot(y))

### ベクトルのノルム（長さ）

ベクトルのノルム

$$
||{\bf{x}}|| = \sqrt{{\bf{x}}^T{\bf{x}}} = \sqrt{ x_1^2+x_2^2 + \cdots + x_m^2}= \sqrt{\sum_{i=1}^m x_i^2}
$$

は，numpy.linalg.norm関数で計算できます．

In [ ]:
print(x)
xnorm = np.linalg.norm(x)
print(xnorm**2)

# 内積を用いて，定義通りに計算
xnorm = np.sqrt(np.dot(x,x))
print(xnorm**2)

### 行列とベクトルの積

同様に，行列とベクトルの積

$$
 {\bf{y}} = A {\bf{x}}
 =
 \begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1n} \\
 a_{21} & a_{22} & \cdots & a_{2n} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mn}
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
 \begin{bmatrix}
 \sum_{j=1} a_{1j} x_j \\
 \sum_{j=1} a_{2j} x_j \\
 \vdots \\
 \sum_{j=1} a_{mj} x_j
 \end{bmatrix}
$$

もnumpy.dotで計算できます．

In [4]:
A = np.array([[1,2,3],[1,2,-1]])
print('A\n', A)
x = np.array([4, -5, 6])
print('x\n',x)
Ax = np.dot(A,x)
print('A x\n', Ax)

# 省略表現
Ax = A.dot(x)
print('A x\n', Ax)

# 簡単表現
Ax = A @ x
print('A x\n', Ax)


A
 [[ 1  2  3]
 [ 1  2 -1]]
x
 [ 4 -5  6]
A x
 [ 12 -12]
A x
 [ 12 -12]
A x
 [ 12 -12]


### 行列の積

行列と行列の積も同様です．

In [5]:
A = np.array([[1,2,3],[1,2,-1]])
print('A\n', A)
B = np.array([[4, 1], [-5, 1], [6, 1]])
print('B\n',B)
AB = np.dot(A,B)
print('A B\n', AB)

# 省略表現
AB = A.dot(B)
print('A B\n', AB)

# 簡単表現
AB = A @ B
print('A B\n', AB)


A
 [[ 1  2  3]
 [ 1  2 -1]]
B
 [[ 4  1]
 [-5  1]
 [ 6  1]]
A B
 [[ 12   6]
 [-12   2]]
A B
 [[ 12   6]
 [-12   2]]
A B
 [[ 12   6]
 [-12   2]]


行列の積は，順番が重要です．

行列$A$と行列$B$の積をその順番を入れ替えて，$AB$と$BA$を計算してみます．


In [6]:
A = np.array([[1,2,3],[1,2,-1],[3,2,1]])
print('A\n', A)
B = np.array([[4, 1, 3], [-5, 1, 2], [6, 1, 1]])
print('B\n',B)

print('----\n')
print('AB')
AB = np.dot(A, B)
print(AB)

print('BA')
BA = np.dot(B, A)
print(BA)


A
 [[ 1  2  3]
 [ 1  2 -1]
 [ 3  2  1]]
B
 [[ 4  1  3]
 [-5  1  2]
 [ 6  1  1]]
----

AB
[[ 12   6  10]
 [-12   2   6]
 [  8   6  14]]
BA
[[ 14  16  14]
 [  2  -4 -14]
 [ 10  16  18]]


### 正方行列のトレース

正方行列$A$のトレースは，

$$
 tr(A) =
 \begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
 \vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mm}
 \end{bmatrix} = a_{11} + a_{22} + \cdots + a_{mm}
$$

のように定義されます．

これは，numpyでは，numpy.trace(A)で計算することができます．


In [7]:
A=np.array([[1,2,3], [2,2,2], [-4, -3, -2]])
print('A\n', A)
print('trace of A = ', np.trace(A))

A
 [[ 1  2  3]
 [ 2  2  2]
 [-4 -3 -2]]
trace of A =  1


### トレースの性質

トレースの性質として，以下の二つは重要です．

$$
    tr(A+B) = tr(A) + tr(B)
$$
    あるいは，
$$
    tr(AB) = tr(BA)
$$

以下のコードは，これらが成り立つことを具体的な行列で確かめています．


In [8]:
A=np.array([[1,2,3], [2,2,2], [-4, -3, -2]])
print('A\n', A)
print('trace of A = ', np.trace(A))
B=np.array([[1,1,1], [2,2,2], [3,3,3]])
print('B\n', B)
print('trace of B = ', np.trace(B))

# tr(A+B)
print('\n=== tr(A+B) = tr(A) + tr(B) ===')
print('trace of A + B = ', np.trace(A+B))
print('tr(A) + tr(B) = ', np.trace(A) + np.trace(B))

# trac(AB)
print('\n=== tr(AB) = tr(BA) ===')
print('tr(AB) = ', np.trace(A.dot(B)))
print('tr(BA) = ', np.trace(B.dot(A)))

A
 [[ 1  2  3]
 [ 2  2  2]
 [-4 -3 -2]]
trace of A =  1
B
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
trace of B =  6

=== tr(A+B) = tr(A) + tr(B) ===
trace of A + B =  7
tr(A) + tr(B) =  7

=== tr(AB) = tr(BA) ===
tr(AB) =  10
tr(BA) =  10


### 2次形式

２次形式は，以下のように定義されます．

$$
      {\bf{x}}^T A {\bf{x}} = \begin{bmatrix} x_1 &  x_2 & \cdots & x_m \end{bmatrix}
      \begin{bmatrix}
        a_{11} & a_{12} & \cdots & a_{1m} \\
        a_{21} & a_{22} & \cdots & a_{2m} \\
        \vdots & \vdots & \ddots & \vdots \\
        a_{m1} & a_{m2} & \cdots & a_{mm}
      \end{bmatrix}
      \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_m \end{bmatrix}
      = \sum_{i=1}^m \sum_{j=1}^m a_{ij} x_i x_j
$$

以下のコードでは，$\bf{x}^T A \bf{x}$を具体的な行列，ベクトルでnumpy.dotをつかって，定義通りに計算しています．

In [9]:
A=np.array([[1,2,3], [2,2,2], [3, 2, 3]])
print('A\n', A)
b = np.array([1,-2,1])
print('b\n', b)
qf = np.dot(b.T, A.dot(b))
print('b^TAb = ', qf)


A
 [[1 2 3]
 [2 2 2]
 [3 2 3]]
b
 [ 1 -2  1]
b^TAb =  2


### フロベニウス・ノルム

行列の全ての要素の２乗の和の平方根

\begin{align*}
  ||A|| = \sqrt{\sum_{i=1}^m \sum_{j=1}^n a_{ij}^2}
\end{align*}

をフロベニウス・ノルムと呼びます．

これは，トレースを使って，

$$
||A|| = \sqrt{tr(A A^T)} = \sqrt{tr(A^T A)}
$$

のように計算することも可能です．

以下のコードは，それを確かめています．

In [10]:
A=np.array([[1,2,3], [4,5,6]])
print('A\n', A)
print('Frobenius norm = ', np.linalg.norm(A))

# tr(A A^T)
print('\n=== tr(A A^T) ===')
AAT = A.dot(A.T)
print('A A^T\n', AAT)
trAAT = np.trace(AAT)
print('tr(A A^T) = ', trAAT)
print('sqrt(tr(A A^T)) = ', np.sqrt(trAAT))

# tr(A^T A)
print('\n=== tr(A^T A) ===')
ATA = np.dot(A.T, A)
print('A^T A\n', ATA)
trATA = np.trace(ATA)
print('tr(A^T A) = ', trATA)
print('sqrt(tr(A^T A)) = ', np.sqrt(trATA))


A
 [[1 2 3]
 [4 5 6]]
Frobenius norm =  9.539392014169456

=== tr(A A^T) ===
A A^T
 [[14 32]
 [32 77]]
tr(A A^T) =  91
sqrt(tr(A A^T)) =  9.539392014169456

=== tr(A^T A) ===
A^T A
 [[17 22 27]
 [22 29 36]
 [27 36 45]]
tr(A^T A) =  91
sqrt(tr(A^T A)) =  9.539392014169456


### 行列の簡約化（Reduced Raw Echelon Form)

sympy を用いて，行列
$$
\begin{bmatrix}
2 & 3 & 6 \\
4 & 5 & 7
\end{bmatrix}
$$
の簡約化をしてみます．

In [11]:
import sympy as sym

In [12]:
A = sym.Matrix([[2,3,6],[4,5,7]])
print('A\n', A)
(B, Pv) = A.rref()
#print('B\n')
B

A
 Matrix([[2, 3, 6], [4, 5, 7]])


Matrix([
[1, 0, -9/2],
[0, 1,    5]])

### ランク

行列のランクは，簡約化した行列の行の数として定義されます．

ここでは，行列
$$
\begin{bmatrix}
1 & 0 & 2 & 1 \\
2 & 1 & 1 & 0 \\
0 & 1 & 1 & 0
\end{bmatrix}
$$
を簡約化してみます．

In [13]:
A=sym.Matrix([[1,0,2,1], [2,1,1,0], [0,1,1,0]])
print('A\n', A)
(B, Pv) = A.rref()
B

A
 Matrix([[1, 0, 2, 1], [2, 1, 1, 0], [0, 1, 1, 0]])


Matrix([
[1, 0, 0,    0],
[0, 1, 0, -1/2],
[0, 0, 1,  1/2]])

これから，この行列のランクは３であることがわかります．

### numpy でのランクの計算

次に，numpyで同じ行列のランクを計算してみます．

そのために，numpy.linalg.matrix_rankという関数を使います．

In [14]:
A=np.array([[1,0,2,1], [2,1,1,0], [0,1,1,0]])
print('A\n', A)
print('rank(A)=', np.linalg.matrix_rank(A))

A
 [[1 0 2 1]
 [2 1 1 0]
 [0 1 1 0]]
rank(A)= 3


# 三角行列

## 上三角行列

上三角行列
$$
A=\begin{bmatrix}
1 & 0 & 2 & 1 \\
0 & 3 & 1 & 3 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 2
\end{bmatrix}
$$
のトレース$tr(A)$, 行列式$det(A)$, 逆行列$A^{-1}$, 固有値を求めてみます．

まず，転置を計算してみます．
上三角行列の転置は，下三角行列になります．

理論的には，トレースは$tr(A)=1+3+1+2=7$ となり，行列式は$det(A)=1 \times 3 \times 1 \times 2 = 6$となるはずなので，それを確かめてみます．

また，上三角行列の逆行列は上三角行列になるはずなので，それを確かめてみます．

三角行列の固有値は，対角成分に等しいことが知られていますので，行列$A$の固有値を具体的に計算してみます．

最後に上三角行列の2乗，3乗を計算してみます．
上三角行列のべき乗は，上三角行列となることがわかります．


In [15]:
A=np.array([[1,0,2,1], [0,3,1,3], [0,0,1,0], [0,0,0,2]])
print('A\n', A)

print('A.T\n', A.T)

print('trace(A)=', np.trace(A))

print('determinant of A=', np.linalg.det(A))

Ainv = np.linalg.inv(A)
print('Inverse of A\n', Ainv)
print('A Ainv\n', np.dot(A, Ainv))

E, L = np.linalg.eig(A)
print('Eigen Values\n', E)

AA = np.dot(A, A)
AAA = np.dot(A, AA)
print('AA\n', AA)
print('AAA\n', AAA)


A
 [[1 0 2 1]
 [0 3 1 3]
 [0 0 1 0]
 [0 0 0 2]]
A.T
 [[1 0 0 0]
 [0 3 0 0]
 [2 1 1 0]
 [1 3 0 2]]
trace(A)= 7
determinant of A= 6.0
Inverse of A
 [[ 1.          0.         -2.         -0.5       ]
 [ 0.          0.33333333 -0.33333333 -0.5       ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          0.5       ]]
A Ainv
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Eigen Values
 [1. 3. 1. 2.]
AA
 [[ 1  0  4  3]
 [ 0  9  4 15]
 [ 0  0  1  0]
 [ 0  0  0  4]]
AAA
 [[ 1  0  6  7]
 [ 0 27 13 57]
 [ 0  0  1  0]
 [ 0  0  0  8]]


### LU分解

正方行列の簡約化を途中まで（上三角行列になるまで）実行すると，元の行列$A$を下三角行列$L$と上三角行列$U$の積に分解することができます．

これを行列の分解方法をLU分解と言います．
実際には，これに行の番号付けの入れ替えを表す行列$P$を使って，

\begin{align*}
    A = P L U
\end{align*}

のように分解することができます．

以下のコードでは，numply.scipy.linalg.luという関数を使って，行列$A$をLU分解し，元も行列が再構成できることを確かめています．

In [16]:
import numpy as np
from scipy.linalg import lu

# pylint: disable=invalid-name

A = np.array([[1, 2, 2],
              [2, 5, 6],
              [3, 8, 12]])

print("LU decomposition (A = PLU): ")
print("A:\n", A)
P, L, U = lu(A)
print("P: \n", P)
print("L: \n", L)
print("U: \n", U)
print("PLU: \n", P @ L @ U)

LU decomposition (A = PLU): 
A:
 [[ 1  2  2]
 [ 2  5  6]
 [ 3  8 12]]
P: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L: 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]]
U: 
 [[ 3.          8.         12.        ]
 [ 0.         -0.66666667 -2.        ]
 [ 0.          0.         -1.        ]]
PLU: 
 [[ 1.  2.  2.]
 [ 2.  5.  6.]
 [ 3.  8. 12.]]


### 連立方程式の解

scipyを利用して，以下の連立方程式の解を求めてみましょう．

\begin{align*}
    \begin{bmatrix} 3 & 2 & 0 \\ 1 & -1 & 0 \\ 0 & 5 & 1 \end{bmatrix}
    \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} =
    \begin{bmatrix} 2 \\ 4 \\ -1 \end{bmatrix}
\end{align*}

In [17]:
#importing the scipy and numpy packages
from scipy import linalg
import numpy as np

#Declaring the numpy arrays
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

m, n = A.shape

print('m=', m, 'n=', n)

# Augmented matrx [A b]
Ab = np.column_stack((A, b))
print("[A b]\n", Ab)

rankA = np.linalg.matrix_rank(A)
rankAb = np.linalg.matrix_rank(Ab)

print("Rank A=", rankA, "Rank [A b]=", rankAb)

if (rankA != rankAb):
    print("There is no solution!!!")
elif (n != rankA):
    print("There is no uniqe solution\n")
else:

    # Determinant of A
    detA = linalg.det(A)
    print("Determinant is", detA)

    #Passing the values to the solve function
    x = linalg.solve(A, b)

    #printing the result array
    print("The solurion is ", x)

    # A x
    print("A x =", A.dot(x))


m= 3 n= 3
[A b]
 [[ 3  2  0  2]
 [ 1 -1  0  4]
 [ 0  5  1 -1]]
Rank A= 3 Rank [A b]= 3
Determinant is -5.0
The solurion is  [ 2. -2.  9.]
A x = [ 2.  4. -1.]


### 逆行列

numpy.linalg.inv関数を用いて，行列
$$
A=\begin{bmatrix}
2 & 1 & 1 \\
1 & 2 & 1 \\
1 & 1 & 2
\end{bmatrix}
$$
の逆行列を数値計算で求めてみます．


In [24]:
A=np.array([[2,1,1],[1,2,1],[1,1,2]])
print('A\n', A)

print('rank=', np.linalg.matrix_rank(A))

det = np.linalg.det(A)
print('det=', det)

Ainv = np.linalg.inv(A)
print('Inverse of A\n', Ainv)

print('det(A)*A\n', det*Ainv)

# Check for A A^{-1}=I
print('A A^{-1}\n', A.dot(Ainv))

A
 [[2 1 1]
 [1 2 1]
 [1 1 2]]
rank= 3
det= 4.0
Inverse of A
 [[ 0.75 -0.25 -0.25]
 [-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]]
det(A)*A
 [[ 3. -1. -1.]
 [-1.  3. -1.]
 [-1. -1.  3.]]
A A^{-1}
 [[1.00000000e+00 5.55111512e-17 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.11022302e-16 1.00000000e+00]]


### 行列式

正方行列の行列式は，numpy.linalg.det関数で求めることができます．

行列式の性質として，以下のような関係が知られています．

$$
det(A^T)=det(A)
$$

$$
det(A^{-1}) = \frac{1}{det(A)}
$$

$$
det(AB) = det(A) det(B)
$$

In [25]:
A=np.array([[1,-1,2],[2,1,1],[-1,-1,1]])
print('A\n', A)
B=np.array([[1,3,-1], [-1,1,-1], [1,1,-3]])
print('B\n', B)

# det(A)
detA = np.linalg.det(A)
print("det(A) = ", detA)

# det(A^T)
detAT = np.linalg.det(A.T)
print("det(A^T) = ", detAT)

# det(A^{-1})
detAinv = np.linalg.det(np.linalg.inv(A))
print("det(A^{-1}) = ", detAinv)

# det(B)
detB = np.linalg.det(B)
print("det(B) = ", detB)

# det(B^T)
detBT = np.linalg.det(B.T)
print("det(B^T) = ", detBT)

# det(B^{-1})
detBinv = np.linalg.det(np.linalg.inv(B))
print("det(B^{-1}) = ", detBinv)

# det(AB)
detAB = np.linalg.det(A.dot(B))
print("det(AB)=", detAB)

A
 [[ 1 -1  2]
 [ 2  1  1]
 [-1 -1  1]]
B
 [[ 1  3 -1]
 [-1  1 -1]
 [ 1  1 -3]]
det(A) =  2.9999999999999996
det(A^T) =  2.9999999999999996
det(A^{-1}) =  0.3333333333333333
det(B) =  -12.0
det(B^T) =  -12.0
det(B^{-1}) =  -0.08333333333333329
det(AB)= -36.0


### 固有値と固有ベクトル

$A\bf{x} = \lambda \bf{x}$が成り立つとき，$\lambda$を行列$A$の固有値，$\bf{x}$を行列$A$の固有値$\lambda$に対する固有ベクトルと呼びます．

$n$次正方行列の固有値は，重複をふくめて，$n$個存在します．それらをまとめて，行列表現すると

$$
A X = X \Lambda
$$

のように書けます．ここで，$\Lambda$は固有値を対角要素にもつ対角行列で，$X$は対応する固有ベクトルを並べた行列です．

numpy.linalg.eig関数で正方行列の固有値と固有ベクトルを求めることができます．


In [26]:
A=np.array([[0,-1],[1,0]])
print('A\n', A)

[E, V] = np.linalg.eig(A)
print('Eigen Values\n', E)
print('Eiven Vectors\n', V)

A
 [[ 0 -1]
 [ 1  0]]
Eigen Values
 [0.+1.j 0.-1.j]
Eiven Vectors
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


この例から，行列$A$が実行列でも固有値や固有ベクトルは複素数になることがわかります

### 固有値と固有ベクトル

3次実対称行列の場合

In [27]:
A=np.array([[1,2,3], [2,2,1],[3,1,3]])
print('A\n', A)

[L, U] = np.linalg.eig(A)
print('Eigen Values\n', L)
print('Eiven Vectors\n', U)

A
 [[1 2 3]
 [2 2 1]
 [3 1 3]]
Eigen Values
 [ 6.14389545 -1.52834667  1.38445123]
Eiven Vectors
 [[ 0.57392741  0.81866166 -0.02001012]
 [ 0.4431767  -0.33105373 -0.83306533]
 [ 0.68862307 -0.46925101  0.55281258]]


実対象行列の固有値，固有ベクトルは実数となることがわかります．


この行列の対角化，つまり，

$$
U^T A U = U^T U \Lambda = \Lambda
$$

を計算してみます．

In [28]:
print("Eigen Values\n", np.diag(L))
print("U^T A U\n", np.dot(U.T, np.dot(A, U)))

Eigen Values
 [[ 6.14389545  0.          0.        ]
 [ 0.         -1.52834667  0.        ]
 [ 0.          0.          1.38445123]]
U^T A U
 [[ 6.14389545e+00 -1.96662074e-16 -6.19728760e-16]
 [-2.77920928e-16 -1.52834667e+00  3.70210736e-16]
 [-6.83591689e-16  2.65669655e-16  1.38445123e+00]]


### スペクトル分解

逆に，

$$
 A = U \Lambda U^T = \sum_{i=1}^n \lambda_i \bf{u}_i \bf{u}_i^T
$$

を行列$A$のスペクトル分解と呼びます．

In [29]:
print("A\n", A)
print("U L U^{T}\n", np.dot(U, np.dot(np.diag(L), U.T)))

A
 [[1 2 3]
 [2 2 1]
 [3 1 3]]
U L U^{T}
 [[1. 2. 3.]
 [2. 2. 1.]
 [3. 1. 3.]]


このように，もとの行列$A$が再構成できることがわかります．

### 特異値分解

特異値分解は，正方行列のスペクトル分解を一般の長方形の行列に拡張したような概念です．

詳細は，教科書などを参考にしてください．


In [30]:
B=np.array([[1,2,3], [2,2,2]])
print('B\n', B)

[S, D, V] = np.linalg.svd(B, full_matrices=True)

print('S\n', S)
print('D\n', D)
print('V^T\n', V)

print('S D V^T\n', np.dot(S * D, V[:2,:]))


B
 [[1 2 3]
 [2 2 2]]
S
 [[-0.73588229 -0.67710949]
 [-0.67710949  0.73588229]]
D
 [5.00415773 0.97898183]
V^T
 [[-0.41767294 -0.56472711 -0.71178129]
 [ 0.81171587  0.12006923 -0.57157741]
 [ 0.40824829 -0.81649658  0.40824829]]
S D V^T
 [[1. 2. 3.]
 [2. 2. 2.]]


### 一般化逆行列（Moore–Penrose inverse）

[特異値分解との関係]

$A$の特異値分解が，
$$
A = U D V^T
$$
で与えられる時，一般化逆行列$A^{+}$は，
$$
A^{+} = V D^{+} U^{T}
$$
で与えられる．ここで，$D^{+}$は，０以外の対角要素はその逆数をとり，0はそのままにした対角行列

これから，
$$
 A A^{+} = U D V^{T} V D^{+} U^{T} = U D D^{+} U^{T} = U U^{T} = I
$$
となることが確かめられる．


In [31]:
from numpy.linalg import pinv

A = np.array([[1,2,3], [2,2,2]])
print('A\n', A)

PinvA = pinv(A)

print('Moore-Penrose pseudo-invers\n', PinvA)

print('A PinvA\n', np.dot(A, PinvA))

A
 [[1 2 3]
 [2 2 2]]
Moore-Penrose pseudo-invers
 [[-5.00000000e-01  6.66666667e-01]
 [-1.17301862e-16  1.66666667e-01]
 [ 5.00000000e-01 -3.33333333e-01]]
A PinvA
 [[ 1.00000000e+00  1.66533454e-16]
 [-1.11022302e-16  1.00000000e+00]]


## sympy を用いた線形代数

行列の宣言

In [ ]:
A = sym.Matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

   ”ｓｙｍｐｙ．Matrix” をnumpy.arrayに変換

In [ ]:
A_n = sym.matrix2numpy(A)
print(A_n)

零行列

In [ ]:
Zero = sym.Matrix.zeros(2, 3)
print(Zero)

単位行列

In [ ]:
I = sym.Matrix.eye(3,3)
print(I)

対角行列

In [ ]:
D = sym.Matrix.diag(1,2,3)
print(D)

In [ ]:
print(A)
print(A[1,2])
print(A[0,0])
print(A[5])

In [ ]:
B=sym.Matrix([[7,8,9],[4,5,6],[1,2,3]])
print(A)
print(B)
print(A * B)

行列の簡約化（Raw Echelon Form)

In [ ]:
print("A={}".format(A))
(G, Pv) = A.rref()
print("G={}".format(G))

行列のランク

In [ ]:
print(A.rank())
print(B.rank())
print((A * B - I).rank())

行列の逆行列

In [ ]:
C=A * B - I
Cinv = C.inv()
print(Cinv)
print(C * Cinv)