<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/pascal_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from scipy.linalg import pascal

n = 4 # 行列の次数
pascal_matrix = pascal(n)
print(pascal_matrix)

[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]]


In [6]:
# Determinant

for n in range(2,5):
  P = pascal(n)
  print(P)
  print('det=', np.linalg.det(P))

[[1 1]
 [1 2]]
det= 1.0
[[1 1 1]
 [1 2 3]
 [1 3 6]]
det= 1.0
[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]]
det= 0.9999999999999991


In [7]:
# inverse matrices

for n in range(2,5):
  P = pascal(n)
  print(P)
  print('inverse\n', np.linalg.inv(P))

[[1 1]
 [1 2]]
inverse
 [[ 2. -1.]
 [-1.  1.]]
[[1 1 1]
 [1 2 3]
 [1 3 6]]
inverse
 [[ 3. -3.  1.]
 [-3.  5. -2.]
 [ 1. -2.  1.]]
[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]]
inverse
 [[  4.  -6.   4.  -1.]
 [ -6.  14. -11.   3.]
 [  4. -11.  10.  -3.]
 [ -1.   3.  -3.   1.]]
