<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/QR_factorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LU Decomposition

In [ ]:
import numpy as np
from scipy.linalg import lu

A = np.array([[1, 2, -1], [2, 6, 0], [-1, 0, 9]])

print(A)

P, L, U = lu(A)

print('P\n', P)
print('L\n', L)
print('U\n', U)

print(np.dot(P, np.dot(L, U)))

[[ 1  2 -1]
 [ 2  6  0]
 [-1  0  9]]
P
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.33333333  1.        ]]
U
 [[2. 6. 0.]
 [0. 3. 9.]
 [0. 0. 2.]]
[[ 1.  2. -1.]
 [ 2.  6.  0.]
 [-1.  0.  9.]]
