<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/QR_factorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QR factorization



In [3]:
import numpy as np
from numpy.linalg import qr

A = np.array([[1, 2, -1], [2, 6, 0], [-1, 0, 9]])

print(A)

Q, R = qr(A)

print('Q\n', Q)
print('R\n', R)

print('Q * R\n', np.dot(Q, R))
print('Q Q^T\n', np.dot(Q, Q.T))

[[ 1  2 -1]
 [ 2  6  0]
 [-1  0  9]]
Q
 [[-0.40824829  0.12309149  0.90453403]
 [-0.81649658 -0.49236596 -0.30151134]
 [ 0.40824829 -0.86164044  0.30151134]]
R
 [[-2.44948974 -5.71547607  4.0824829 ]
 [ 0.         -2.7080128  -7.87785542]
 [ 0.          0.          1.80906807]]
Q * R
 [[ 1.0000000e+00  2.0000000e+00 -1.0000000e+00]
 [ 2.0000000e+00  6.0000000e+00 -1.6361719e-15]
 [-1.0000000e+00 -5.0430051e-16  9.0000000e+00]]
Q Q^T
 [[ 1.00000000e+00  2.34109027e-16 -1.41501896e-16]
 [ 2.34109027e-16  1.00000000e+00 -6.46683277e-17]
 [-1.41501896e-16 -6.46683277e-17  1.00000000e+00]]
