<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/rref.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def rref(A):
    # 行列をNumPyの形式に変換
#    A = np.array(matrix, dtype=float)
    rows, cols = A.shape

    # ガウスの消去法を実行
    for i in range(min(rows, cols)):
        # 主成分を1にする
        if A[i, i] != 0:
            A[i, :] /= A[i, i]
        else:
            continue

        # 他の行から主成分を除去
        for j in range(rows):
            if i != j:
                A[j, :] -= A[j, i] * A[i, :]

    return A



In [2]:
# 4行3列の行列の例
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
], dtype=float)

print('A\n', A)

# 簡約化された行列を計算
rref_matrix = rref(A)

# 結果を表示
print("簡約化された行列:")
print(rref_matrix)


A
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
簡約化された行列:
[[ 1.  0. -1.]
 [-0.  1.  2.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [3]:
# 任意の行列の例
A = np.array([
    [1, 2, 3, 1],
    [4, 5, 6, 1],
    [7, 8, 9, 1]
], dtype=float)

print('A\n', A)

# 簡約化された行列を計算
rref_matrix = rref(A)

# 結果を表示
print("簡約化された行列:")
print(rref_matrix)

A
 [[1. 2. 3. 1.]
 [4. 5. 6. 1.]
 [7. 8. 9. 1.]]
簡約化された行列:
[[ 1.  0. -1. -1.]
 [-0.  1.  2.  1.]
 [ 0.  0.  0.  0.]]
