<a href="https://colab.research.google.com/github/namoshi/mathAI/blob/master/var_compare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

A=np.array([0, 3, 3, 5, 5, 5, 5, 7, 7, 10])

print('A\n', A)
print('Mean(A)=', np.mean(A))

B = np.array([0, 1, 2, 3, 5, 5, 7, 8, 9, 10])

print('B\n', B)
print('Mean(B)=', np.mean(B))

C = np.array([3, 4, 4, 5, 5, 5, 5, 6, 6, 7])

print('C\n', C)
print('Mean(C)=', np.mean(C))

varA = np.sum(np.power(A, 2))/len(A) - np.mean(A)**2

print('Var(A)={}, sd(A)={}'.format(varA, np.sqrt(varA)))

varB = np.sum(np.power(B, 2))/len(B) - np.mean(B)**2

print('Var(B)={}, sd(B)={}'.format(varB, np.sqrt(varB)))

varC = np.sum(np.power(C, 2))/len(C) - np.mean(C)**2

print('Var(C)={}, sd(C)={}'.format(varC, np.sqrt(varC)))

A
 [ 0  3  3  5  5  5  5  7  7 10]
Mean(A)= 5.0
B
 [ 0  1  2  3  5  5  7  8  9 10]
Mean(B)= 5.0
C
 [3 4 4 5 5 5 5 6 6 7]
Mean(C)= 5.0
Var(A)=6.600000000000001, sd(A)=2.5690465157330262
Var(B)=10.799999999999997, sd(B)=3.2863353450309964
Var(C)=1.1999999999999993, sd(C)=1.095445115010332
